name: Create Package 📦

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  # Build the package
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js 20.x
      uses: actions/setup-node@v3
      with:
        node-version: 20.x

    - name: Build
      run: |
        npm install
        npm run build

    # Upload artifact
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: "MyLo CodeView"
        path: dist/

  # Tag the build
  tag:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ButlerLogic/action-autotag@1.1.2 
      name: Create tag from Manifest
      id: tagger
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
      with:
        strategy: regex
        root: "/public/manifest.json"
        regex_pattern: > 
          "version":\s*"([0-9]+\.[0-9]+\.[0-9]+)"
        tag_prefix: "v"
    - run: echo "${{ steps.tagger.outputs.tagname }}"
    outputs:
      tag: ${{ steps.tagger.outputs.tagname }}

  # Update the release
  release:
    runs-on: ubuntu-latest
    needs: [ build, tag ]
    if: ${{ startsWith(needs.tag.outputs.tag, 'v') }}
    steps:
      - uses: actions/checkout@v4
  
      - uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Zip Contents
        run: |
          cd artifacts/*
          zip -r MyloCodeView.zip *

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: ${{ needs.tag.outputs.tag }}
          prerelease: true
          title: Release ${{ needs.tag.outputs.tag }}
          files: artifacts/**/*.zip